# Generated by Django 5.1.4 on 2024-12-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
